### ISSUE TITLE
Minor optimization suggestion or How to get O(lol) performance

### ISSUE THREAD

**Issue by pkomon** [Phoenix1747/Godot-FOV-Tilemaps#8]
Yeah, another one.

About `get_start_point()` / `get_end_point()`.
(how can this even work, indentation in `get_start_point()` (or at least github does not display it correctly) seems to not be syntax compliant; also there is an empty loop; but nevermind that, cant test it anyway)

First you get arrays of all x and y values in your tilemap; then you sort those arrays and read index 0 to find the smallest/greatest value. I think this is from the Python standard library, so I just googled a little and found out, that `list.sort()` uses the [*timsort algorithm*](https://en.wikipedia.org/wiki/Timsort) for sorting. In general, *NO* ordinary sorting algorithm can have a better worst case performance than *O(n*log(n))*. So is timsort (even tho it's best case performance is *O(n)*). A better alternative for finding the smallest/greatest) number in an unsorted array is just searching sequentially (given that you don't need the sorted list afterwards). That way you always have a performance of *O(n)*.

NB: In fact, you actually can get linear performance, if you know about the distribution of your data. For example, if you have just plain random values, every value is equally propable; lets say 10 values between 1 and 10; take an array that can hold a little more values (say, 14). Now just guess their positions! 

Say values are `1 6 10 8 9 4 3 2 4 7` (just randomly generated); you would sort them in like this:
floor(10/14*value), e.g. 
```
1*14/10 -> 1,4 -> 1
6*14/10 -> 8,4 -> 8
10*14/10 -> 14 -> 14
8*14/10 -> 11,2 -> 11
9*14/10 -> 12,6 -> 12
4*14/10 -> 5,6 -> 5
2*14/10 -> 2,8 -> 2 
3*14/10 -> 4,2 -> 4
4*14/10 -> 5,6 -> 5 (collision) -> 6
7*14/10 -> 9,8 -> 9
```
So now you have `[1, 2,   , 3, 4, 4,  , 6, 7,  , 8, 9,  , 10]`. Now you would "tighten" that array, removing empty spaces, resulting in 2 operations per element (at most) -> `O(n)` for sorting (oh, shouldn't even have multiplied by the actual array size, a smaller number would've been better (accounting for collisions at the end), also the example is a little dumb without decimal places, but you get the idea). Anyway. BOOM. Linear performance for sorting. Problem is, you need to know the distribution of your values for the strategy to work. For normal-distributed values you would take into account the distribution's parameters when guessing (actually calculating) the right index for a given value and reserve more space for more probable values - that way you minimize the probability of collisions; reserving more space than actually necessary can help reduce the number of collisions too. Most algorithms try to analyze the data set given and use this for estimating the indices. [*Proxmap sort*](https://en.wikipedia.org/wiki/Proxmap_sort) is a good example of an algorithm using this kind of strategy. Uhh, yep, this doesn't even have anything to do with this issue. Still I wrote it. pLox HeLp

**Comment by NuclearPhoenixx** [comment]
Done, by using Godot's own min and max array functions. Nothing to be done from my side here :smile:.

See #7.
